/**
 * Venice AI Video Rating System
 * Manages winner selections across comparison grids
 * Uses browser localStorage for persistence
 *
 * Auto-generated by setup.js - DO NOT EDIT MANUALLY
 */

// Configuration objects (generated from config.json)
const SCENE_CONFIG = {{SCENE_CONFIG}};

const MODEL_NAMES = {{MODEL_NAMES}};

const VIDEO_FILE_MAPPING = {{VIDEO_FILE_MAPPING}};

// Export to global scope for dashboard access
window.SCENE_CONFIG = SCENE_CONFIG;
window.MODEL_NAMES = MODEL_NAMES;
window.VIDEO_FILE_MAPPING = VIDEO_FILE_MAPPING;

// Storage key for localStorage
const STORAGE_KEY = 'venice-ai-winners';

/**
 * Get all winner selections from localStorage
 */
function getAllWinners() {
  const data = localStorage.getItem(STORAGE_KEY);
  return data ? JSON.parse(data) : {};
}

/**
 * Get winner for a specific scene
 */
function getWinner(sceneId) {
  const winners = getAllWinners();
  return winners[sceneId] || null;
}

/**
 * Set winner for a specific scene
 */
function setWinner(sceneId, modelId) {
  const winners = getAllWinners();
  const videoInfo = VIDEO_FILE_MAPPING[sceneId]?.[modelId];
  winners[sceneId] = {
    winner: modelId,
    timestamp: new Date().toISOString(),
    sceneName: SCENE_CONFIG[sceneId]?.title || sceneId,
    modelName: MODEL_NAMES[modelId] || modelId,
    generationTime: videoInfo?.generationTime || null
  };
  localStorage.setItem(STORAGE_KEY, JSON.stringify(winners));
  return winners[sceneId];
}

/**
 * Remove winner selection for a scene
 */
function clearWinner(sceneId) {
  const winners = getAllWinners();
  delete winners[sceneId];
  localStorage.setItem(STORAGE_KEY, JSON.stringify(winners));
}

/**
 * Toggle winner selection (set if not selected, clear if selected)
 */
function toggleWinner(sceneId, modelId) {
  const current = getWinner(sceneId);
  if (current && current.winner === modelId) {
    clearWinner(sceneId);
    return null;
  } else {
    return setWinner(sceneId, modelId);
  }
}

/**
 * Initialize grid page with winner selection
 */
function initializeGrid(sceneId) {
  const videoCells = document.querySelectorAll('.video-cell');
  const currentWinner = getWinner(sceneId);

  videoCells.forEach(cell => {
    const modelId = cell.dataset.model;

    // Mark current winner
    if (currentWinner && currentWinner.winner === modelId) {
      cell.classList.add('winner-selected');
    }

    // Add click handler
    cell.addEventListener('click', () => {
      const result = toggleWinner(sceneId, modelId);

      // Update UI
      videoCells.forEach(c => c.classList.remove('winner-selected'));
      if (result) {
        cell.classList.add('winner-selected');
      }
    });

    // Add hover overlay for selection
    const overlay = document.createElement('div');
    overlay.className = 'rating-overlay';
    overlay.innerHTML = `
      <div class="rating-overlay-content">
        <svg class="checkmark-icon" width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
          <circle cx="24" cy="24" r="20" stroke="#DD3300" stroke-width="3" fill="rgba(221, 51, 0, 0.2)"/>
          <path d="M14 24L20 30L34 16" stroke="#DD3300" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <div class="rating-text">Click to Select Winner</div>
      </div>
    `;
    cell.appendChild(overlay);
  });
}

/**
 * Get video file path for a scene and model
 */
function getVideoPath(sceneId, modelId) {
  if (VIDEO_FILE_MAPPING[sceneId] && VIDEO_FILE_MAPPING[sceneId][modelId]) {
    const folder = SCENE_CONFIG[sceneId].folder;
    const videoInfo = VIDEO_FILE_MAPPING[sceneId][modelId];
    const filename = videoInfo.filename || videoInfo; // Backward compatibility
    return `../../videos/${folder}/${filename}`;
  }
  return null;
}

/**
 * Export all selections as JSON
 */
function exportSelections() {
  const winners = getAllWinners();
  const exportData = {
    project: '{{PROJECT_TITLE}}',
    exportDate: new Date().toISOString(),
    totalScenes: Object.keys(SCENE_CONFIG).length,
    selectedScenes: Object.keys(winners).length,
    selections: winners
  };

  const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `venice-ai-winners-${new Date().toISOString().split('T')[0]}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Clear all selections
 */
function clearAllSelections() {
  if (confirm(`Clear all winner selections? This cannot be undone.`)) {
    localStorage.removeItem(STORAGE_KEY);
    location.reload();
  }
}

// Make functions globally available
window.getAllWinners = getAllWinners;
window.getWinner = getWinner;
window.setWinner = setWinner;
window.clearWinner = clearWinner;
window.toggleWinner = toggleWinner;
window.initializeGrid = initializeGrid;
window.getVideoPath = getVideoPath;
window.exportSelections = exportSelections;
window.clearAllSelections = clearAllSelections;
