/**
 * Venice AI Video Rating System
 * Manages winner selections across comparison grids
 * Uses browser localStorage for persistence
 *
 * Auto-generated by setup.js - DO NOT EDIT MANUALLY
 */

// Configuration objects (generated from config.json)
const SCENE_CONFIG = {{SCENE_CONFIG}};

const MODEL_NAMES = {{MODEL_NAMES}};

const VIDEO_FILE_MAPPING = {{VIDEO_FILE_MAPPING}};

// Export to global scope for dashboard access
window.SCENE_CONFIG = SCENE_CONFIG;
window.MODEL_NAMES = MODEL_NAMES;
window.VIDEO_FILE_MAPPING = VIDEO_FILE_MAPPING;

// Storage key for localStorage
const STORAGE_KEY = 'venice-ai-winners';

/**
 * Get all winner selections from localStorage
 */
function getAllWinners() {
  const data = localStorage.getItem(STORAGE_KEY);
  return data ? JSON.parse(data) : {};
}

/**
 * Get winner for a specific scene
 */
function getWinner(sceneId) {
  const winners = getAllWinners();
  return winners[sceneId] || null;
}

/**
 * Set winner for a specific scene
 */
function setWinner(sceneId, modelId) {
  const winners = getAllWinners();
  const videoInfo = VIDEO_FILE_MAPPING[sceneId]?.[modelId];
  winners[sceneId] = {
    winner: modelId,
    timestamp: new Date().toISOString(),
    sceneName: SCENE_CONFIG[sceneId]?.title || sceneId,
    modelName: MODEL_NAMES[modelId] || modelId,
    generationTime: videoInfo?.generationTime || null
  };
  localStorage.setItem(STORAGE_KEY, JSON.stringify(winners));
  return winners[sceneId];
}

/**
 * Remove winner selection for a scene
 */
function clearWinner(sceneId) {
  const winners = getAllWinners();
  delete winners[sceneId];
  localStorage.setItem(STORAGE_KEY, JSON.stringify(winners));
}

/**
 * Toggle winner selection (set if not selected, clear if selected)
 */
function toggleWinner(sceneId, modelId) {
  const current = getWinner(sceneId);
  if (current && current.winner === modelId) {
    clearWinner(sceneId);
    return null;
  } else {
    return setWinner(sceneId, modelId);
  }
}

/**
 * Create and inject modal HTML and CSS for full-screen video viewing
 */
function injectModal() {
  // Only inject once
  if (document.getElementById('video-modal')) return;

  // Inject modal CSS
  const style = document.createElement('style');
  style.textContent = `
    .video-modal {
      display: none;
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: rgba(0, 0, 0, 0.95);
      z-index: 10000;
      align-items: center;
      justify-content: center;
    }
    .video-modal.active {
      display: flex;
    }
    .video-modal-content {
      position: relative;
      width: 90vw;
      height: 90vh;
      max-width: 1920px;
      max-height: 1080px;
    }
    .video-modal-video {
      width: 100%;
      height: 100%;
      object-fit: contain;
    }
    .video-modal-close {
      position: absolute;
      top: -50px;
      right: 0;
      background: rgba(221, 51, 0, 0.2);
      border: 1px solid #DD3300;
      color: #DD3300;
      padding: 12px 24px;
      border-radius: 6px;
      font-size: 16px;
      font-weight: 600;
      cursor: pointer;
      transition: all 0.3s ease;
    }
    .video-modal-close:hover {
      background: #DD3300;
      color: #FFFFFF;
    }
    .video-modal-info {
      position: absolute;
      top: -50px;
      left: 0;
      color: #B0CED1;
      font-size: 14px;
      font-weight: 600;
    }
    .view-full-button {
      position: absolute;
      top: 12px;
      left: 12px;
      background: rgba(0, 0, 0, 0.9);
      color: #C8E3FD;
      padding: 8px 12px;
      border-radius: 6px;
      font-size: 12px;
      font-weight: 600;
      z-index: 16;
      cursor: pointer;
      border: 1px solid rgba(200, 227, 253, 0.3);
      transition: all 0.3s ease;
      opacity: 0;
      pointer-events: none;
    }
    .video-cell:hover .view-full-button {
      opacity: 1;
      pointer-events: auto;
    }
    .view-full-button:hover {
      background: rgba(200, 227, 253, 0.2);
      border-color: #C8E3FD;
    }
  `;
  document.head.appendChild(style);

  // Inject modal HTML
  const modal = document.createElement('div');
  modal.id = 'video-modal';
  modal.className = 'video-modal';
  modal.innerHTML = `
    <div class="video-modal-content">
      <div class="video-modal-info"></div>
      <button class="video-modal-close">Close (ESC)</button>
      <video class="video-modal-video" controls loop></video>
    </div>
  `;
  document.body.appendChild(modal);

  // Add event listeners
  const closeBtn = modal.querySelector('.video-modal-close');
  const video = modal.querySelector('.video-modal-video');

  closeBtn.addEventListener('click', closeModal);
  modal.addEventListener('click', (e) => {
    if (e.target === modal) closeModal();
  });
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && modal.classList.contains('active')) {
      closeModal();
    }
  });
}

/**
 * Open modal with specific video
 */
function openModal(videoSrc, modelName) {
  const modal = document.getElementById('video-modal');
  const video = modal.querySelector('.video-modal-video');
  const info = modal.querySelector('.video-modal-info');

  video.src = videoSrc;
  info.textContent = modelName;
  modal.classList.add('active');
  video.play();
}

/**
 * Close modal and stop video playback
 */
function closeModal() {
  const modal = document.getElementById('video-modal');
  const video = modal.querySelector('.video-modal-video');

  modal.classList.remove('active');
  video.pause();
  video.src = '';
}

/**
 * Initialize grid page with winner selection
 */
function initializeGrid(sceneId) {
  const videoCells = document.querySelectorAll('.video-cell');
  const currentWinner = getWinner(sceneId);

  // Inject modal on first initialization
  injectModal();

  videoCells.forEach(cell => {
    const modelId = cell.dataset.model;
    const videoEl = cell.querySelector('video');
    const videoSrc = videoEl ? videoEl.querySelector('source')?.src : null;

    // Create "View Full" button
    const viewFullBtn = document.createElement('button');
    viewFullBtn.className = 'view-full-button';
    viewFullBtn.textContent = '🔍 View Full';
    viewFullBtn.addEventListener('click', (e) => {
      e.stopPropagation(); // Prevent triggering winner selection
      if (videoSrc) {
        openModal(videoSrc, MODEL_NAMES[modelId]);
      }
    });
    cell.appendChild(viewFullBtn);

    // Mark current winner
    if (currentWinner && currentWinner.winner === modelId) {
      cell.classList.add('winner-selected');
    }

    // Add click handler
    cell.addEventListener('click', () => {
      const result = toggleWinner(sceneId, modelId);

      // Update UI
      videoCells.forEach(c => c.classList.remove('winner-selected'));
      if (result) {
        cell.classList.add('winner-selected');
      }
    });

    // Add hover overlay for selection
    const overlay = document.createElement('div');
    overlay.className = 'rating-overlay';
    overlay.innerHTML = `
      <div class="rating-overlay-content">
        <svg class="checkmark-icon" width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
          <circle cx="24" cy="24" r="20" stroke="#DD3300" stroke-width="3" fill="rgba(221, 51, 0, 0.2)"/>
          <path d="M14 24L20 30L34 16" stroke="#DD3300" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <div class="rating-text">Click to Select Winner</div>
      </div>
    `;
    cell.appendChild(overlay);
  });
}

/**
 * Get video file path for a scene and model
 */
function getVideoPath(sceneId, modelId) {
  if (VIDEO_FILE_MAPPING[sceneId] && VIDEO_FILE_MAPPING[sceneId][modelId]) {
    const folder = SCENE_CONFIG[sceneId].folder;
    const videoInfo = VIDEO_FILE_MAPPING[sceneId][modelId];
    const filename = videoInfo.filename || videoInfo; // Backward compatibility
    return `../../videos/${folder}/${filename}`;
  }
  return null;
}

/**
 * Export all selections as JSON
 */
function exportSelections() {
  const winners = getAllWinners();
  const exportData = {
    project: '{{PROJECT_TITLE}}',
    exportDate: new Date().toISOString(),
    totalScenes: Object.keys(SCENE_CONFIG).length,
    selectedScenes: Object.keys(winners).length,
    selections: winners
  };

  const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `venice-ai-winners-${new Date().toISOString().split('T')[0]}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Clear all selections
 */
function clearAllSelections() {
  if (confirm(`Clear all winner selections? This cannot be undone.`)) {
    localStorage.removeItem(STORAGE_KEY);
    location.reload();
  }
}

// Make functions globally available
window.getAllWinners = getAllWinners;
window.getWinner = getWinner;
window.setWinner = setWinner;
window.clearWinner = clearWinner;
window.toggleWinner = toggleWinner;
window.initializeGrid = initializeGrid;
window.getVideoPath = getVideoPath;
window.exportSelections = exportSelections;
window.clearAllSelections = clearAllSelections;
window.injectModal = injectModal;
window.openModal = openModal;
window.closeModal = closeModal;
